name: Generate JS Docs # this runs JSDocs on all JS files

on: [push] 

permissions:
  contents: write

jobs: 
  jsdocs: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependency
        run: npm install -g jsdoc

      - name: Making JS Docs
        run: jsdoc -r .

      - name: Commit and Push Docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update JS docs"
          git push
