name: Generate JS Docs # this runs JSDocs on all JS files


on: [push] 

permissions:
  contents: write
  pull-requests: write

jobs: 
  jsdocs: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependency
        run: npm install -g jsdoc

      - name: Making JS Docs
        run: jsdoc -r .

      - name: Commit and Push Docs Thru Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update JS docs"
          branch: jsdocs-update
          token: ${{ secrets.GITHUB_TOKEN }}
