name: Generate JS Docs # this runs JSDocs on all JS files

on: [push]

permissions:
  contents: write #

jobs:
  jsdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependency
        run: npm install -g jsdoc

      - name: Making JS Docs and Print to Output
        run: |
          jsdoc -r . | tee
