name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint JS and CSS with Biome
        run: npm run lint:css-js

      - name: Check formatting for JS and CSS with Prettier
        run: npx prettier --check '**/*.{js,css}' || echo "JS/CSS Formatting issues detected"

      - name: Lint HTML with HTMLHint
        run: npm run lint:html

      - name: Check HTML formatting with Prettier
        run: npx prettier --check '**/*.html' || echo "HTML Formatting issues detected"
