name: Unit Tests # name of the test

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Install jest-environment-jsdom
        run: npm install --save-dev jest-environment-jsdom
      - name: Unit Test
        run: npm test -- ./admin/cipipeline/unit.test.js
      - name: CRUD Unit Tests
        run: npm test -- ./admin/cipipeline/createCardUnit.test.js
